---
- hosts: web
  become: yes
  become_method: sudo

  tasks:
    - name: Upgrade all packages on servers
      apt:
        upgrade: yes

    - name: Install packages
      apt: pkg={{ item }}
      with_items:
          - nodejs
          - npm
          - nginx

    - name: Update Node
      shell:
        cmd: npm install -g n && n stable

    - name: Install Yarn
      shell:
        cmd: npm install -g yarn

    - name: Install project dependencies
      command: chdir=/vagrant/OpenBlog yarn install

    - name: Install extra dependencies (codebase err)
      command: chdir=/vagrant/OpenBlog/packages/app yarn add sharp

    - name: Build Project     
      command: chdir=/vagrant/OpenBlog/packages/api yarn build

    - name: Create Deamons
      copy: 
          src: "./scripts/"
          dest: "/etc/systemd/system/"

    - name: Start API Daemon
      service:
          enabled: yes
          state: started
          daemon_reload: yes
          name: api.service

    - name: Enable APP Daemon
      service:
          enabled: yes
          state: started
          daemon_reload: yes
          name: app.service

    - name: start nginx 
      service:
          name: nginx
          state: started