---
- name: Install Node packages
  apt: pkg={{ item }}
  with_items:
    - nodejs
    - npm

- name: Update Node
  community.general.npm:
    name: n
    global: yes
    
- shell: n stable

- name: Install Yarn
  community.general.npm:
    name: yarn
    global: yes