---
- hosts: db
  become: yes
  become_method: sudo

  tasks:
    - name: Include variables file
      ansible.builtin.include_vars:
        dir: group_vars
        ignore_files:
          - 'secret.example.yml'
        extensions:
          - 'yml'

    - name: Ping
      shell:
        cmd: echo "ping"