---
- hosts: all
  become: yes

  tasks:
    - name: Install ssh-key for {{ ansible_facts['user_id'] }} in {{ ansible_play_hosts_all }}
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', '../pkey.pub') }}"

    - name: IPv6 bugfix
      ansible.builtin.replace:
        path: /etc/gai.conf
        regexp: '#precedence ::ffff:0:0\/96  100'
        replace: 'precedence ::ffff:0:0/96  100'

    - name: Upgrade all packages on servers
      apt:
        upgrade: yes

    - name: Ensure chrony (for time synchronization) is installed.
      apt:
        name: chrony
        state: present
        update_cache: yes
    - name: Ensure chrony is running
      service:
        name: chronyd
        state: started
        enabled: yes
