---
- hosts: all
  become: yes

  tasks:
    - name: IPv6 bugfix
      ansible.builtin.replace:
        path: /etc/gai.conf
        regexp: '#precedence ::ffff:0:0\/96  100'
        replace: 'precedence ::ffff:0:0/96  100'

    - name: Upgrade all packages on servers
      apt:
        upgrade: yes

    - name: Ensure chrony (for time synchronization) is installed.
      apt:
        name: chrony
        state: present
        update_cache: yes
    - name: Ensure chrony is running
      service:
        name: chronyd
        state: started
        enabled: yes
