---
- hosts: web
  become: yes
  become_method: sudo

  tasks:
    - name: Include variables file
      ansible.builtin.include_vars:
        dir: group_vars
        ignore_files:
          - 'secret.example.yml'
        extensions:
          - 'yml'

    - name: Install packages
      apt: pkg={{ item }}
      with_items:
        - nodejs
        - npm
        - nginx
        - git

    - name: Update Node
      shell:
        cmd: npm install -g n && n stable

    - name: Install Yarn
      shell:
        cmd: npm install -g yarn

    - name: Clone repo
      git:
        repo: https://github.com/Totoratsu/OpenBlog.git
        dest: /opt/OpenBlog
        clone: yes
        force: yes

    - name: Install project dependencies
      command: chdir=/opt/OpenBlog yarn install

    - name: Install extra dependencies (codebase err)
      command: chdir=/opt/OpenBlog/packages/app yarn add sharp

    - name: Build Project     
      command: chdir=/opt/OpenBlog/packages/api yarn build

    - name: Create Deamons
      copy: 
        src: "./../scripts/"
        dest: "/etc/systemd/system/"

    - name: Start API Daemon
      service:
        enabled: yes
        state: started
        daemon_reload: yes
        name: api.service
      environment:
        DB_PASS: "{{ DB_PASS }}"
        DB_USER: "{{ DB_USER }}"
        SESSION_SECRET: "{{ SESSION_SECRET }}"
        DB_HOST: db

    - name: Enable APP Daemon
      service:
        enabled: yes
        state: started
        daemon_reload: yes
        name: app.service

    - name: start nginx 
      service:
        name: nginx
        state: started