---
- hosts: web
  become: yes
  become_method: sudo

  roles:
    - nodejs

  vars:
    nfs_ip: 192.168.56.13

  tasks:
    - name: Include variables file
      ansible.builtin.include_vars:
        dir: group_vars
        ignore_files:
          - 'secret.example.yml'
        extensions:
          - 'yml'

    - name: Install packages
      apt: pkg={{ item }}
      with_items:
        - nginx
        - nfs-common

    - name: Create NFS directory
      file:
        path: /mnt/nfs_clientshare
        state: directory        
        owner: vagrant
        group: vagrant
        mode: '0775'

    - name: Mount NFS directory
      ansible.posix.mount:
        src: "{{ nfs_ip }}:/mnt/nfs_share"
        path: /mnt/nfs_clientshare
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

#    - name: Create Deamons
#      copy: 
#        src: "./../scripts/"
#        dest: "/etc/systemd/system/"
#
#    - name: Start API Daemon
#      service:
#        enabled: yes
#        state: started
#        daemon_reload: yes
#        name: api.service
#      environment:
#        DB_PASS: "{{ DB_PASS }}"
#        DB_USER: "{{ DB_USER }}"
#        SESSION_SECRET: "{{ SESSION_SECRET }}"
#        DB_HOST: db
#
#    - name: Enable APP Daemon
#      service:
#        enabled: yes
#        state: started
#        daemon_reload: yes
#        name: app.service

    - name: start nginx 
      service:
        name: nginx
        state: started